(TeX-add-style-hook "Dirichlet"
 (lambda ()
    (LaTeX-add-labels
     "sec:Dirichlet"
     "thm:harm-form"
     "eq:harm1"
     "eq:harm2"
     "prop:harm-realteil-hol"
     "prop:max-prinzip-harm"
     "defin:rwp"
     "prop:dirichlet-eindeutig"
     "thm:poisson"
     "eq:residuensatz"
     "cor:harm-darstellung"
     "cor:harm-konvergenz"
     "thm:harnack"
     "eq:P-absch"
     "prop:harm-rf"
     "cor:pd-rechenregeln"
     "lemma:perron"
     "eq:v-absch"
     "def:perron"
     "eq:dirichlet-rand"
     "lemma:zsh-komp"
     "lemma:regulär-trennen"
     "thm:dirichlet"
     "thm:reg-rand"
     "rem:reg-rand")))

