(TeX-add-style-hook "header"
 (lambda ()
    (LaTeX-add-index-entries
     "#1")
    (LaTeX-add-bibliographies
     "biblio")
    (LaTeX-add-environments
     "thm"
     "lemma"
     "prop"
     "cor"
     "defin"
     "bsp"
     "rem")
    (TeX-add-symbols
     "C"
     "S"
     "P"
     "epsilon"
     "phi"
     "d"
     "Re"
     "Im")
    (TeX-run-style-hooks
     "fontspec"
     "todonotes"
     "mathtools"
     "amsthm"
     "makeidx"
     "tikz"
     "microtype"
     "hyperref"
     "xparse"
     "amsmath"
     "babel"
     "amssymb"
     "biblatex"
     "scrpage2"
     "latex2e"
     "scrartcl10"
     "scrartcl"
     "ngerman"
     "twoside"
     "headsepline")))

